<a href="https://colab.research.google.com/github/BiondiConsulting/Cola-Test/blob/master/GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [3]:
torch.cuda.is_available()

True

In [0]:
device = torch.device('cuda')

In [6]:
a = torch.rand(3,3)
a

tensor([[0.1006, 0.3451, 0.3625],
        [0.1311, 0.0985, 0.1349],
        [0.5481, 0.9585, 0.0467]])

In [7]:
b =  torch.rand(3,3).to(device)
b

tensor([[0.2338, 0.6566, 0.5571],
        [0.4932, 0.7862, 0.2193],
        [0.2321, 0.6282, 0.6057]], device='cuda:0')

In [9]:
c = torch.rand(3,3).cuda()
c

tensor([[0.2029, 0.0409, 0.6625],
        [0.3107, 0.6177, 0.8204],
        [0.7061, 0.7032, 0.4082]], device='cuda:0')

In [0]:
import time

In [21]:
start = time.time()
a = torch.ones(400,400)
for _ in range (100000):
  a += a
duration = time.time() - start
print(f'CPU time = {duration}')


start = time.time()
b = torch.ones(400,400).to(device)
for _ in range (100000):
  b += b
duration = time.time() - start
print(f'GPU time = {duration}')

CPU time = 4.287049770355225
GPU time = 0.914215087890625
