<a href="https://colab.research.google.com/github/BiondiConsulting/Cola-Test/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [3]:
y = torch.tensor([[1,2,3], [2,3,4],[0,0,0]])
y

tensor([[1, 2, 3],
        [2, 3, 4],
        [0, 0, 0]])

In [5]:
y = torch.tensor([[1,2,3], [2,3,4],[0,0,0]], dtype=torch.float)
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [17]:
t=torch.ones(1, 2, dtype=torch.int)
t

tensor([[1, 1]], dtype=torch.int32)

In [18]:
p=torch.zeros(5,4,3, dtype=torch.float)
p

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [22]:
z=torch.randn(3,4, dtype=torch.float)
print (f'This is what you get with randn =\n{z}')

This is what you get with randn =
tensor([[ 0.6426, -0.3078, -0.6616, -0.1817],
        [-1.0185,  0.8595,  0.6855,  1.1298],
        [ 0.8425, -1.4977,  0.1540, -1.1258]])


In [24]:
p[2,:,0]

tensor([0., 0., 0., 0.])

In [29]:
y.size()

torch.Size([3, 3])

In [0]:
t = torch.rand(3,3)

In [33]:
t+y

tensor([[1.9131, 2.2933, 3.6920],
        [2.2825, 3.7304, 4.2495],
        [0.8220, 0.4499, 0.5962]])

In [34]:
t*y

tensor([[0.9131, 0.5866, 2.0761],
        [0.5649, 2.1911, 0.9982],
        [0.0000, 0.0000, 0.0000]])

In [35]:
t*24

tensor([[21.9154,  7.0389, 16.6086],
        [ 6.7789, 17.5290,  5.9890],
        [19.7284, 10.7973, 14.3093]])

In [36]:
torch.squeeze(y.reshape(1,9))

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [40]:
y.sum(0)
# here we sum only the elements of the first column in y

tensor([3., 5., 7.])

In [41]:
torch.max(y)

tensor(4.)

In [44]:
values, indices = torch.max(y,0)
print(values)
print(indices)
# the torch.max fuction used on y at the index 0 returns a tuple value. This is why we need to give 2 parameters to the variable

tensor([2., 3., 4.])
tensor([1, 1, 1])


In [49]:
y[1,0].item() ==2

True

In [48]:
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [50]:
y[1,0]==2

tensor(True)

# Let's make a sync trial