<a href="https://colab.research.google.com/github/BiondiConsulting/Cola-Test/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [2]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [3]:
y = torch.tensor([[1,2,3], [2,3,4],[0,0,0]])
y

tensor([[1, 2, 3],
        [2, 3, 4],
        [0, 0, 0]])

In [4]:
y = torch.tensor([[1,2,3], [2,3,4],[0,0,0]], dtype=torch.float)
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [5]:
t=torch.ones(1, 2, dtype=torch.int)
t

tensor([[1, 1]], dtype=torch.int32)

In [6]:
p=torch.zeros(5,4,3, dtype=torch.float)
p

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [7]:
z=torch.randn(3,4, dtype=torch.float)
print (f'This is what you get with randn =\n{z}')

This is what you get with randn =
tensor([[ 0.3993, -0.3003, -0.6171, -1.1122],
        [-1.0287,  0.8278,  0.9550, -1.4880],
        [ 1.1930, -0.0110, -0.4704, -0.1375]])


In [8]:
p[2,:,0]

tensor([0., 0., 0., 0.])

In [9]:
y.size()

torch.Size([3, 3])

In [0]:
t = torch.rand(3,3)

In [11]:
t+y

tensor([[1.1933, 2.8411, 3.4819],
        [2.6046, 3.8490, 4.3331],
        [0.4811, 0.5183, 0.1715]])

In [12]:
t*y

tensor([[0.1933, 1.6821, 1.4457],
        [1.2093, 2.5471, 1.3325],
        [0.0000, 0.0000, 0.0000]])

In [13]:
t*24

tensor([[ 4.6394, 20.1855, 11.5653],
        [14.5112, 20.3766,  7.9953],
        [11.5473, 12.4382,  4.1164]])

In [14]:
torch.squeeze(y.reshape(1,9))

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [15]:
y.sum(0)
# here we sum only the elements of the first column in y

tensor([3., 5., 7.])

In [16]:
torch.max(y)

tensor(4.)

In [17]:
values, indices = torch.max(y,0)
print(values)
print(indices)
# the torch.max fuction used on y at the index 0 returns a tuple value. This is why we need to give 2 parameters to the variable

tensor([2., 3., 4.])
tensor([1, 1, 1])


In [18]:
y[1,0].item() ==2

True

In [19]:
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [20]:
y[1,0]==2

tensor(True)

# Let's make a sync trial

In [0]:
import pandas as pd


In [0]:
data = pd.DataFrame(y)

In [23]:
data

0           1           2
0  tensor(1.)  tensor(2.)  tensor(3.)
1  tensor(2.)  tensor(3.)  tensor(4.)
2  tensor(0.)  tensor(0.)  tensor(0.)

In [0]:
data = y.numpy()

In [0]:
data2 = pd.DataFrame(data)

In [33]:
data2.astype(int)

0  1  2
0  1  2  3
1  2  3  4
2  0  0  0